title: Boris Gorelik
email: boris@gorelik.net
description: >- # this means to ignore newlines until "baseurl:"
  Data Science &amp; Communication Consultant and Advisor
  | AI, Machine Learning, Data Visualization
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:year/:month/:day/:title

blog_theme: light

paginate: 25
paginate_path: "/blog/page:num/"

social:
  github: bgbg # Add your GitHub handle
  linkedin: boris-gorelik-phd # Add your LinkedIn handle
  twitter-x: boris_gorelik # Add your Twitter handle
  youtube: gorelikboris # Add your Youtube handle

nav_pages:
  - name: About
    url: /
  - name: Directions Matters Newsletter
    url: "https://directionmatters.substack.com/"
  - name: Blog
    url: /blog
  - name: אני בעברית
    url: https://he.gorelik.net/

assets:
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}
  source_maps: false
  sources:
    - _assets/icons
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/yarn

# Build settings
#theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
